[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  targetPort = 3000
  port = 8888
  autoLaunch = false

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200